#!/bin/bash
# Copyright (c) Paul Tagliamonte <paultag@ubuntu.com>, 2012, under the terms
# and conditions of the Expat license.

set -e

DIST="sid"
SBUILD=/var/sbuild

if [ "x$1" != "x" ]; then
    DIST=$1
fi

cd $SBUILD/$DIST.d
variants=$(ls | grep -v "default" | sed "s/$DIST-//g")
for x in $variants; do
    echo "I: $x $DIST"
    echo "apt-get update -y" | sb-maint $x $DIST
    echo "apt-get upgrade -y" | sb-maint $x $DIST
done
