'\" t
.\"     Title: sb-clean
.\"    Author: Paul Tagliamonte <paultag@ubuntu.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: June 1st 2012
.\"    Manual: sb Manual
.\"    Source: sb-clean.txt
.\"  Language: English
.\"
.TH "SB\-CLEAN" "1" "June 1st 2012" "sb\-clean\&.txt" "sb Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sb-clean \- clean an overlay
.SH "SYNOPSIS"
.sp
\fBsb\-clean\fR [\fIvariant\fR] [\fIdist\fR]
.SH "DESCRIPTION"
.sp
\fIsb\-clean(1)\fR cleans the overlay folder out, because \fIsbo(1)\fR, by default, does not purge the overlay chroot\&. We call this leaving the chroot hot\&. Since the default use\-case is to put the unionfs overlay point on tmpfs, this isn\(cqt a big deal, since when you reboot, your chroot will be magically clean\&.
.sp
Invoke this tool to manually clean the overlay out\&.
.SH "OPTIONS"
.PP
\fBvariant\fR
.RS 4
This option (always first) is the variant of chroot to use\&. This is something like "clang" or "gcc"\&. This option defaults to "default"\&. It\(cqs common to set up symbolic links to provide sane behavior\&.
.RE
.PP
\fBdist\fR
.RS 4
This option (always second) is the suite of chroots to use, such as "sid" or "testing"\&. This option defaults to "sid", but this behavior may change soon to default to the last changelog target, not counting
\fIUNRELEASED\fR\&.
.RE
.SH "AUTHORS"
.sp
Paul Tagliamonte <\m[blue]\fBpaultag@ubuntu\&.com\fR\m[]\&\s-2\u[1]\d\s+2> for sb
.SH "SEE ALSO"
.sp
sb(1), sb\-create(1), sb\-login(1), sb\-maint(1), sb\-prehook(1), sb\-posthook(1), sb\-update(1), sbo(1)
.SH "AUTHOR"
.PP
\fBPaul Tagliamonte\fR <\&paultag@ubuntu\&.com\&>
.RS 4
Author.
.RE
.SH "NOTES"
.IP " 1." 4
paultag@ubuntu.com
.RS 4
\%mailto:paultag@ubuntu.com
.RE
